# Generated by Django 5.1.5 on 2026-04-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='equipe/')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ouvinte', models.CharField(max_length=150)),
                ('nome_musica', models.CharField(max_length=255)),
                ('lido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('nome_programa', models.CharField(max_length=150)),
                ('nome_locutor', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
    ]
