# Generated by Django 5.1.5 on 2026-04-04 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='nome_locutor',
        ),
        migrations.AddField(
            model_name='programacao',
            name='locutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='core.equipe'),
        ),
    ]
