# Generated by Django 5.1.5 on 2026-04-04 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_programacao_nome_locutor_programacao_locutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidomusica',
            old_name='nome_musica',
            new_name='pedido',
        ),
    ]
