# Generated by Django 5.1.5 on 2026-04-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_musica_pedidomusica_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='programacao',
            options={'ordering': ['horario_inicio']},
        ),
        migrations.AlterField(
            model_name='programacao',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], null=True),
        ),
        migrations.AddField(
            model_name='programacao',
            name='dias_semana',
            field=models.ManyToManyField(blank=True, related_name='programas', to='core.diasemana'),
        ),
    ]
