# Generated by Django 5.1.5 on 2026-04-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diasemana_alter_programacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='dia_semana',
        ),
    ]
