# Generated by Django 5.1.5 on 2026-04-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horário da Leitura')),
                ('count', models.IntegerField(default=0, verbose_name='Ouvintes Totais')),
                ('unique_count', models.IntegerField(default=0, verbose_name='Ouvintes Únicos')),
            ],
            options={
                'verbose_name': 'Estatística de Ouvinte',
                'verbose_name_plural': 'Estatísticas de Ouvintes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
