# Generated by Django 5.0.6 on 2024-06-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_options_remove_sponsor_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors/mobile/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image_web',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors/web/'),
        ),
    ]
