# Generated by Django 5.0.6 on 2024-06-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_alter_sponsor_image_mobile_alter_sponsor_image_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
