# Generated by Django 5.0.6 on 2024-06-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_sponsor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={},
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='display_order',
        ),
    ]
