# Generated by Django 5.1.2 on 2025-01-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0011_alter_sponsor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField(max_length=255)),
                ('imagem_app', models.ImageField(upload_to='patrocinador/app/')),
                ('imagem_site', models.ImageField(upload_to='patrocinador/site/')),
            ],
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
