# Generated by Django 5.1.2 on 2025-01-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0012_patrocinador_delete_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='imagem_app',
            field=models.ImageField(upload_to='patrocinador_app/'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='imagem_site',
            field=models.ImageField(upload_to='patrocinador_site/'),
        ),
    ]
