# Generated by Django 5.1.5 on 2026-04-03 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0013_alter_patrocinador_imagem_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
