# Generated by Django 5.1.5 on 2025-01-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_noticias_imagem_noticias_updated_at_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='rodape',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticias',
            name='subtitulo',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
