# Generated by Django 5.1.5 on 2026-04-04 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_imagem_rodape_noticias_subtitulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticias',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_editadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
